language: ruby
cache: bundler
rvm:
  - 2.4.1
before_script: 
  - bundle exec rake db:setup
install: 
  - npm install
  - bundle exec rake assets:precompile
  - bundle install --jobs=3 --retry=3
script: 
  - bundle exec rake
